### ISSUE TITLE
How to create dynamic OID filter rule for CISCO syslog TRAP

### ISSUE THREAD

**Issue by cristobal85** [patrickpr/trapdirector#27] opened 2020-02-06 11:07 UTC
In CISCO systems when send a syslog trap, trap has a different OID each time. How do I create a filter rule for these traps?

![image](https://user-images.githubusercontent.com/11557433/73931528-c1d02180-48d8-11ea-9490-110d0d3cee46.png)

![image](https://user-images.githubusercontent.com/11557433/73931786-2c815d00-48d9-11ea-8de7-3b60472d8520.png)

**Comment by patrickpr** [comment] 2020-02-06 18:21
Hi,
This is a duplicate of issue#16, but I didn't have time to add it to display and in docs, so here is how : 

- Create a handler with one of your traps
- Create the rule you want and test it (the rule tester won't work after).

Let's say your rule is : 

`( $1$ = 4 ) & ( $2$ ~ "GigabitEthernet2" )`

with : 
- `$1$ = .1.3.6.1.4.1.9.9.4.1.2.3.1.2.92180`
- `$2$ = .1.3.6.1.4.1.9.9.4.1.2.3.1.5.92180`

Change in your rule `$1$` with `_OID(.1.3.6.1.4.1.9.9.4.1.2.3.1.2.\*)` and $2$ with  `_OID(.1.3.6.1.4.1.9.9.4.1.2.3.1.5.\*)`

Your rule should look like : 

`( _OID(.1.3.6.1.4.1.9.9.4.1.2.3.1.2.\*) = 4 ) & ( _OID(.1.3.6.1.4.1.9.9.4.1.2.3.1.5.\*) ~ "GigabitEthernet2" )`

- Save your handler and check your rule in handler list.

- Rule tester will NOT work

- Note : * means one number (like it this example the last one), and ** means one or more number

**Comment by patrickpr** [comment] 2020-02-06 22:19
Added a commit to be able to insert regexp directly into GUI (download latest master) : 
- Edit or create a trap handler
- In "Trap Objects definition", enter the OID with '*' in 'Add an OID'
- You can now use $X$ assigned to the regexp OID, and rule testing will also work. 
- You can also use the value it in display.

Note : in case regexp matches multiple OIDs in the trap, only the first one will be tested.

**Comment by patrickpr** [comment] 2020-02-13 15:00
In version 1.0.3 with doc. Reopen in case of problems.

**Closed by patrickpr** 2020-02-13 15:00 UTC
Labels: duplicate, enhancement
